### ISSUE TITLE
Select field values

### ISSUE THREAD

**Issue by AJannik** [cookgreen/ArenaModdingTool#6]
There are some fields like when creating a kingdom the culture field where it would be awesome if I could click on that field and select the culture from all existing cultures in this mod project. e.g:
![item](https://user-images.githubusercontent.com/67471557/145372668-7a2c492b-08f4-4073-922a-2387cccea588.PNG)

**Comment by cookgreen** [comment]
OK

**Comment by cookgreen** [comment]
Actaully you can double-click the field so that you can select the culture from the prompt window since the cultures in different xml files @AJannik

**Comment by cookgreen** [comment]
Fixed, add a combox for the culture
